const allQuestions = [
  // --- Heart Anatomy Questions ---
  {
    question: "Which chamber of the heart receives oxygen-poor blood from the body?",
    options: ["Left atrium", "Right atrium", "Left ventricle", "Right ventricle"],
    answer: 1,
    explanation:
      "The right atrium receives deoxygenated blood from the body via the superior and inferior vena cava.",
    difficulty: "easy",
    category: "heart",
  },
  {
    question: "Which valve is located between the left atrium and left ventricle?",
    options: ["Tricuspid valve", "Pulmonary valve", "Mitral (bicuspid) valve", "Aortic valve"],
    answer: 2,
    explanation: "The mitral (bicuspid) valve separates the left atrium and left ventricle.",
    difficulty: "easy",
    category: "heart",
  },
  {
    question: "Which vessel carries oxygenated blood from the lungs to the heart?",
    options: ["Pulmonary artery", "Pulmonary vein", "Aorta", "Superior vena cava"],
    answer: 1,
    explanation: "The pulmonary veins carry oxygenated blood from the lungs to the left atrium.",
    difficulty: "easy",
    category: "heart",
  },

  // --- CBET / Device Questions: 100-question master bank ---
  {
    question: "A 120 V device draws 2.0 A. Approximately how much power does it consume?",
    options: ["60 W", "120 W", "240 W", "480 W"],
    answer: 2,
    explanation: "Power equals voltage multiplied by current: 120 V \u00d7 2.0 A = 240 W.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A 12 V source is applied across a 6 \u03a9 resistor. What current should flow?",
    options: ["0.5 A", "2 A", "6 A", "72 A"],
    answer: 1,
    explanation: "Ohm\u2019s law gives I = V/R = 12/6 = 2 A.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "Two 100 \u03a9 resistors are connected in series. What is the total resistance?",
    options: ["50 \u03a9", "100 \u03a9", "200 \u03a9", "10,000 \u03a9"],
    answer: 2,
    explanation: "Series resistances add directly, so 100 \u03a9 + 100 \u03a9 = 200 \u03a9.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "Two identical 100 \u03a9 resistors are connected in parallel. What is the equivalent resistance?",
    options: ["25 \u03a9", "50 \u03a9", "100 \u03a9", "200 \u03a9"],
    answer: 1,
    explanation: "Two equal resistors in parallel have half the resistance of either resistor: 50 \u03a9.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "Which component primarily stores energy in an electric field?",
    options: ["Inductor", "Capacitor", "Diode", "Fuse"],
    answer: 1,
    explanation: "A capacitor stores electrical energy in an electric field.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "Which component is intended to conduct current primarily in one direction?",
    options: ["Transformer", "Resistor", "Diode", "Inductor"],
    answer: 2,
    explanation: "A diode is designed to conduct primarily in the forward direction and block reverse current.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A fuse repeatedly opens after replacement. What is the BEST next action?",
    options: ["Install a higher-rated fuse", "Bypass the fuse temporarily", "Find the overcurrent cause before replacing it again", "Replace the power cord only"],
    answer: 2,
    explanation: "Repeated fuse opening indicates an underlying overcurrent fault that must be diagnosed; increasing or bypassing protection is unsafe.",
    difficulty: "medium",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A transformer is most directly used to:",
    options: ["Store digital data", "Change AC voltage levels and provide isolation when designed for it", "Convert resistance to capacitance", "Measure leakage current"],
    answer: 1,
    explanation: "Transformers transfer AC energy magnetically and can step voltage up/down and provide isolation.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A 10 k\u03a9 resistor measures approximately 2 \u03a9 while still installed in a circuit. What should the technician consider FIRST?",
    options: ["The resistor must be open", "Parallel circuit paths may be affecting the reading", "The meter battery always causes low readings", "The resistor value increases under test"],
    answer: 1,
    explanation: "In-circuit resistance readings can be lowered by parallel paths; isolate the component as appropriate before concluding it failed.",
    difficulty: "medium",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "When measuring voltage with a digital multimeter, the meter is normally connected:",
    options: ["In series with the load", "Across the two points being measured", "Only to protective earth", "Across a removed fuse"],
    answer: 1,
    explanation: "Voltage is a potential difference and is measured across two points.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "When measuring current directly with a multimeter, the meter is normally placed:",
    options: ["In parallel with the source", "In series with the circuit path", "Across protective earth and neutral", "Across the load without opening the circuit"],
    answer: 1,
    explanation: "Direct current measurement requires the meter to become part of the current path, so it is placed in series.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "An electrolytic capacitor has a visibly bulged top. What is the MOST appropriate interpretation?",
    options: ["Normal aging with no electrical significance", "Possible capacitor failure requiring evaluation/replacement", "Evidence the circuit is underloaded", "Proof the fuse is oversized"],
    answer: 1,
    explanation: "Bulging is a common physical sign of electrolytic capacitor degradation or failure.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A bridge rectifier in a power supply primarily converts:",
    options: ["DC to AC", "AC to pulsating DC", "Analog to digital", "Frequency to resistance"],
    answer: 1,
    explanation: "A rectifier uses diodes to convert AC into pulsating DC.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A regulator stage in a DC power supply is primarily intended to:",
    options: ["Increase mechanical airflow", "Maintain a stable output despite input/load changes", "Generate protective earth", "Measure battery capacity"],
    answer: 1,
    explanation: "Voltage regulation keeps the DC output near its intended value as line and load conditions change.",
    difficulty: "medium",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "An oscilloscope is especially useful when a technician needs to evaluate:",
    options: ["Only static resistance", "Waveform shape, amplitude, and timing", "Equipment inventory status", "Mechanical torque"],
    answer: 1,
    explanation: "Oscilloscopes display voltage versus time, making waveform and timing problems visible.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A 5 V digital logic rail measures 3.1 V under load but 5.0 V with the load disconnected. What does this MOST strongly suggest?",
    options: ["A possible overloaded supply or excessive series resistance", "A guaranteed software fault", "An open protective-earth conductor", "Normal operation for all logic circuits"],
    answer: 0,
    explanation: "A rail that collapses only under load points toward excessive load, weak supply regulation, or resistance in the power path.",
    difficulty: "hard",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "An NTC thermistor commonly has what behavior as temperature rises?",
    options: ["Resistance increases sharply", "Resistance decreases", "Capacitance becomes zero", "It becomes an ideal short at all temperatures"],
    answer: 1,
    explanation: "For a negative-temperature-coefficient thermistor, resistance decreases as temperature increases.",
    difficulty: "medium",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A relay allows a low-power control circuit to:",
    options: ["Directly measure SpO2", "Switch another electrical circuit", "Store calibration coefficients", "Convert AC frequency to pressure"],
    answer: 1,
    explanation: "A relay uses an electrically controlled coil or solid-state mechanism to switch another circuit.",
    difficulty: "easy",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "A technician suspects an intermittent connector. Which technique is MOST useful?",
    options: ["Replace every board first", "Monitor the relevant signal while gently stressing the connector/cable under controlled conditions", "Increase fuse size", "Disable alarms during testing"],
    answer: 1,
    explanation: "Controlled manipulation while monitoring the affected signal can reproduce and localize connector-related intermittents.",
    difficulty: "hard",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "When measuring very low resistance, which factor can create a significant error?",
    options: ["Room lighting", "Test-lead and contact resistance", "Display font size", "Network subnet mask"],
    answer: 1,
    explanation: "Lead and contact resistance can be comparable to the resistance being measured and must be accounted for.",
    difficulty: "medium",
    category: "cbet",
    topic: "electronics",
  },
  {
    question: "An infusion pump has a nonfunctional occlusion alarm but delivers the programmed rate accurately. What should be done?",
    options: ["Return it to service with a note", "Remove it from service until alarm function is restored and verified", "Use it only during day shift", "Lower the programmed rate"],
    answer: 1,
    explanation: "Required alarm functionality is part of safe device performance; accurate flow alone does not make the pump acceptable.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "After repairing a life-support device, what should occur before it is returned to clinical use?",
    options: ["Only a cosmetic inspection", "Required functional and safety verification with documented results", "A nurse should try it first", "The service history should be cleared"],
    answer: 1,
    explanation: "Post-repair verification must demonstrate that the device meets applicable functional and safety requirements before release.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A three-wire power cord has a damaged protective-earth conductor. The device should be:",
    options: ["Used if it powers on", "Removed from service until the protective-earth path is corrected and verified", "Used only on battery while plugged in", "Released if leakage is not measured"],
    answer: 1,
    explanation: "A compromised protective-earth path can defeat a key protection against shock and requires correction.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "Which instrument is specifically designed to evaluate electrical safety parameters such as leakage current and protective-earth resistance?",
    options: ["Defibrillator analyzer", "Electrical safety analyzer", "Infusion device analyzer", "Tachometer"],
    answer: 1,
    explanation: "An electrical safety analyzer is designed for measurements such as leakage current and protective-earth continuity/resistance.",
    difficulty: "easy",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "Why should a technician follow the manufacturer\u2019s specified fuse type and rating?",
    options: ["To make the device run faster", "Because the fuse is part of the device\u2019s designed overcurrent protection", "To eliminate preventive maintenance", "Because all fuses with the same size are equivalent"],
    answer: 1,
    explanation: "Fuse current, voltage, speed, and interrupt characteristics are selected as part of the protection design.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A medical device arrives from an outside repair vendor. Before clinical use, the BEST action is to:",
    options: ["Assume the vendor completed all checks", "Complete the facility\u2019s required incoming/return-to-service verification", "Replace the battery regardless of condition", "Send it directly to the requesting unit"],
    answer: 1,
    explanation: "The facility should verify required safety, function, configuration, and documentation before returning the device to use.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A device has an intermittent fault that can disable a critical alarm. Even if the fault cannot be reproduced every time, the BEST action is to:",
    options: ["Return it with instructions to watch it", "Quarantine it until the safety-related fault is resolved", "Disable the affected alarm", "Use it only for low-acuity patients"],
    answer: 1,
    explanation: "An intermittent safety-related failure can recur unpredictably and should not be accepted for clinical service.",
    difficulty: "hard",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "Which documentation BEST supports a decision to return repaired equipment to service?",
    options: ["A note that the device turned on", "Completed service documentation including relevant test results", "A parts invoice only", "An email stating the repair was difficult"],
    answer: 1,
    explanation: "Documented verification results provide evidence that required performance and safety checks were completed.",
    difficulty: "medium",
    category: "cbet",
    topic: "service",
  },
  {
    question: "A damaged strain relief on a power cord is significant because it can:",
    options: ["Only change appearance", "Allow conductor damage and create shock or intermittent-fault risk", "Improve flexibility", "Reduce network bandwidth"],
    answer: 1,
    explanation: "Strain relief protects conductors from repeated bending and pull forces; damage can lead to exposed or intermittent conductors.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "Which factor should MOST strongly guide a preventive-maintenance interval?",
    options: ["Technician preference alone", "Manufacturer recommendations, device risk, regulatory requirements, and facility policy", "Sticker inventory", "The color of the equipment"],
    answer: 1,
    explanation: "PM strategy should be risk- and evidence-based and consistent with applicable requirements and organizational policy.",
    difficulty: "medium",
    category: "cbet",
    topic: "service",
  },
  {
    question: "During incoming inspection, a device has the correct model but an accessory is not approved for that device. What is the BEST response?",
    options: ["Use it if the connector fits", "Verify compatibility and approved use before clinical release", "Modify the connector", "Ignore the accessory because the main unit passed"],
    answer: 1,
    explanation: "Physical fit does not establish compatibility; accessory approval and validated performance must be confirmed.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A technician discovers fluid intrusion inside a powered medical device. What is the FIRST priority?",
    options: ["Power it repeatedly to dry it", "Remove it from service and make it safe before further evaluation", "Increase ventilation and return it", "Replace the display only"],
    answer: 1,
    explanation: "Potential fluid intrusion creates electrical and corrosion risks; the device should be made safe and evaluated before energizing.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A device\u2019s audible alarm works, but its required visual alarm indicator does not. The device is:",
    options: ["Fully acceptable because one alarm path works", "Not ready for service until required alarm functionality is restored", "Acceptable in brightly lit rooms", "Acceptable if the user signs a waiver"],
    answer: 1,
    explanation: "If the device design requires both alarm modalities, loss of one means alarm performance is incomplete.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "When servicing equipment connected to mains power, lockout/tagout procedures are intended primarily to:",
    options: ["Improve network security", "Control hazardous energy and prevent unexpected energization", "Increase battery runtime", "Calibrate sensors"],
    answer: 1,
    explanation: "Lockout/tagout controls hazardous energy so equipment cannot be unexpectedly energized during applicable service work.",
    difficulty: "easy",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A recall notice applies to a model in the hospital inventory. What is the BEST first operational step?",
    options: ["Delete the assets from inventory", "Identify affected units/serial numbers and follow the recall or correction instructions", "Wait for users to report failures", "Replace every unit regardless of scope"],
    answer: 1,
    explanation: "Recall management begins by determining which assets are affected and implementing the specified corrective action.",
    difficulty: "medium",
    category: "cbet",
    topic: "service",
  },
  {
    question: "Why is post-repair configuration verification important after a main control board replacement?",
    options: ["It only changes cosmetic settings", "Incorrect configuration can alter alarms, options, calibration, or clinical behavior", "It prevents cleaning", "It guarantees network access"],
    answer: 1,
    explanation: "Replacement boards may require model-, option-, or calibration-specific configuration before safe clinical use.",
    difficulty: "hard",
    category: "cbet",
    topic: "service",
  },
  {
    question: "A technician uses a substitute power supply not specified for a medical device. What is the main concern?",
    options: ["The label may be a different color", "Electrical characteristics, isolation, EMC, or safety performance may no longer be validated", "The device will always draw less power", "The screen will necessarily be brighter"],
    answer: 1,
    explanation: "Unapproved power supplies can alter safety and performance characteristics even when voltage appears compatible.",
    difficulty: "hard",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "A device passes functional tests but fails a required electrical-safety test after repair. What is the correct disposition?",
    options: ["Return it because function is more important", "Keep it out of service until the safety failure is corrected and retested", "Repeat only the functional test", "Document the failure and release it"],
    answer: 1,
    explanation: "Required safety criteria must be met as well as functional criteria before clinical release.",
    difficulty: "medium",
    category: "cbet",
    topic: "safety",
  },
  {
    question: "Which analyzer is most appropriate for verifying delivered energy from a defibrillator?",
    options: ["Electrical safety analyzer only", "Defibrillator analyzer", "Infusion device analyzer", "Pressure manometer only"],
    answer: 1,
    explanation: "A defibrillator analyzer measures parameters such as delivered energy and can evaluate synchronization and other functions depending on model.",
    difficulty: "easy",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An electrosurgical unit fails output verification at several load settings. Which test instrument is most appropriate?",
    options: ["ESU analyzer", "NIBP simulator", "Pulse oximeter", "Sound-level meter"],
    answer: 0,
    explanation: "An ESU analyzer is designed to measure electrosurgical output and related performance.",
    difficulty: "easy",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "To verify an NIBP monitor without using a patient, a technician would commonly use a:",
    options: ["Patient simulator with NIBP capability", "Defibrillator paddle", "Flowmeter only", "Photometer"],
    answer: 0,
    explanation: "An NIBP-capable simulator can provide controlled pressure/pulse conditions for monitor evaluation.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An SpO2 monitor reads erratically on multiple known-good sensors. Which check is MOST useful early in troubleshooting?",
    options: ["Verify the problem with an appropriate simulator/tester and inspect the sensor interface", "Replace the display immediately", "Disable low-saturation alarms", "Increase speaker volume"],
    answer: 0,
    explanation: "Controlled simulation helps separate monitor/interface faults from patient, sensor, and environmental variables.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An infusion pump delivers 105 mL when programmed to deliver 100 mL during a controlled test. What should the technician do FIRST?",
    options: ["Adjust calibration immediately without repeating the test", "Compare the result with the manufacturer\u2019s allowable accuracy and test method", "Return it because the error is only 5 mL", "Replace the keypad"],
    answer: 1,
    explanation: "Acceptance depends on the specified test method and tolerance; verify against the manufacturer\u2019s performance criteria before adjustment.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A ventilator\u2019s measured tidal volume differs from its displayed value. Which device is most appropriate for independent verification?",
    options: ["Ventilator/flow analyzer", "Electrical safety analyzer only", "Defibrillator analyzer", "ECG simulator"],
    answer: 0,
    explanation: "A ventilator or respiratory flow analyzer independently measures flow, volume, pressure, and related respiratory parameters.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An ECG monitor displays a stable 60 bpm when connected to a simulator set to 120 bpm. What is the BEST next step?",
    options: ["Assume the simulator is wrong", "Verify simulator setup/leads, then evaluate the monitor signal path and settings", "Replace the power cord", "Change the NIBP cuff"],
    answer: 1,
    explanation: "Confirm the test setup first, then trace the ECG acquisition and processing path if the discrepancy remains.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A pulse oximeter\u2019s SpO2 value drops when bright surgical lighting is directed at the sensor. This most likely suggests:",
    options: ["Optical interference at the sensor", "A defective NIBP pump", "Incorrect ECG gain", "A failed protective-earth conductor"],
    answer: 0,
    explanation: "Strong ambient light can interfere with optical pulse-oximetry sensing if shielding or sensor placement is inadequate.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A defibrillator charges normally but delivers substantially low energy into the analyzer. Which area deserves investigation?",
    options: ["Energy-storage/discharge path and output components", "NIBP tubing", "SpO2 sensor cable", "Printer paper only"],
    answer: 0,
    explanation: "Normal charging with low delivered energy points toward the storage/discharge/output path rather than unrelated subsystems.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An infusion pump occlusion alarm activates at a much higher pressure than specified. Why is this important?",
    options: ["It may delay detection of a blocked infusion line", "It only affects battery charging", "It improves flow accuracy", "It prevents air-in-line detection"],
    answer: 0,
    explanation: "An excessive occlusion-alarm threshold can delay recognition of downstream blockage and increase clinical risk.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A suction regulator cannot maintain the set vacuum when flow is applied. What should be checked?",
    options: ["Vacuum source, tubing/leaks, regulator performance, and test setup", "ECG electrodes", "Defibrillator pads", "Network DNS settings"],
    answer: 0,
    explanation: "Loss of vacuum under load can arise from supply limitations, leaks, restrictions, or regulator malfunction.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An anesthesia machine oxygen analyzer reads lower than a calibrated reference. What should occur before clinical release?",
    options: ["Ignore the difference if flowmeters work", "Evaluate/calibrate or repair the oxygen-monitoring function per procedure", "Disable oxygen alarms", "Increase nitrous oxide flow"],
    answer: 1,
    explanation: "Accurate oxygen concentration monitoring is safety-critical and discrepancies must be resolved before use.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A syringe pump intermittently alarms \u201cocclusion\u201d with no downstream restriction. Which cause is MOST plausible?",
    options: ["Faulty pressure sensing or mechanical drive resistance", "Incorrect ECG lead placement", "A failed SpO2 emitter", "Excessive NIBP cuff size"],
    answer: 0,
    explanation: "False occlusion alarms can result from pressure-sensing errors, drive friction, syringe seating, or related mechanical factors.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A patient monitor\u2019s ECG waveform is noisy only when plugged into one wall outlet and becomes clean on battery. What should be investigated?",
    options: ["Room power quality/grounding and environmental interference", "The NIBP cuff size", "The monitor\u2019s printer paper", "The SpO2 alarm limit only"],
    answer: 0,
    explanation: "The location- and mains-dependent pattern points toward power/grounding or environmental interference rather than a purely internal ECG fault.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A fetal monitor transducer produces intermittent signal loss when its cable is flexed near the connector. What is the BEST next step?",
    options: ["Inspect and test the cable/connector for an intermittent conductor", "Replace the monitor main board first", "Increase alarm volume", "Recalibrate NIBP"],
    answer: 0,
    explanation: "A flex-dependent failure strongly implicates the cable or connector and should be reproduced and localized.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An ultrasound transducer has a visible crack in its housing. The MOST appropriate action is to:",
    options: ["Continue use if the image looks normal", "Remove it from service and evaluate according to manufacturer/facility procedure", "Cover the crack with tape", "Increase output power"],
    answer: 1,
    explanation: "Physical damage can affect electrical safety, infection control, acoustic performance, and internal integrity.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A temperature monitor consistently reads 2 \u00b0C high with a known reference. What should be verified before calibration?",
    options: ["Probe type, reference accuracy, connections, and specified test conditions", "Only the device serial number", "Network gateway", "Speaker volume"],
    answer: 0,
    explanation: "Test setup and reference accuracy must be confirmed before concluding that calibration is required.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A device battery shows normal voltage with no load but collapses under load. This MOST strongly indicates:",
    options: ["Reduced battery capacity/high internal resistance", "A guaranteed display failure", "Normal battery behavior", "Incorrect protective-earth resistance"],
    answer: 0,
    explanation: "A degraded battery may maintain open-circuit voltage but sag excessively when current is demanded.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A ventilator passes startup self-test but fails to reach commanded pressure during a test lung evaluation. Which is the BEST troubleshooting direction?",
    options: ["Check circuit leaks, valves, flow/pressure generation, sensors, and test setup", "Replace the display", "Change the network hostname", "Ignore the failure because self-test passed"],
    answer: 0,
    explanation: "A passed self-test does not guarantee delivered respiratory performance; the pneumatic path and measurement system must be evaluated.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A medical gas flowmeter ball sticks at several positions. What is the safest response?",
    options: ["Tap it during patient use", "Remove it from service and evaluate/replace it according to procedure", "Lubricate it with any available oil", "Increase supply pressure above specification"],
    answer: 1,
    explanation: "A sticking flow indicator can produce unreliable gas delivery and should be corrected using approved procedures.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "An ECG lead-off alarm never activates when a lead is disconnected during testing. The monitor should be:",
    options: ["Returned because the waveform still displays", "Removed from service until the alarm function is corrected and verified", "Used only with telemetry", "Released if NIBP works"],
    answer: 1,
    explanation: "Lead-off detection is a required monitoring/alarm function and must operate correctly before release.",
    difficulty: "medium",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A defibrillator synchronization marker does not consistently align with the simulated R wave. What is the concern?",
    options: ["Synchronized cardioversion timing may be unsafe or ineffective", "Only printer quality is affected", "Battery runtime will increase", "Pacing output will always be normal"],
    answer: 0,
    explanation: "Synchronization depends on accurate R-wave detection; misalignment can cause shock delivery at an inappropriate point in the cardiac cycle.",
    difficulty: "hard",
    category: "cbet",
    topic: "devices",
  },
  {
    question: "A networked medical device can ping its gateway but cannot reach a server by hostname. Which issue is MOST likely?",
    options: ["DNS/name-resolution problem", "Open power fuse", "Failed SpO2 sensor", "Incorrect NIBP cuff"],
    answer: 0,
    explanation: "Gateway connectivity with hostname failure suggests name resolution should be investigated.",
    difficulty: "medium",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "Two devices are accidentally configured with the same static IP address. What symptom is likely?",
    options: ["Intermittent or conflicting network connectivity", "Higher battery capacity", "Lower leakage current", "Improved wireless roaming"],
    answer: 0,
    explanation: "Duplicate IP addresses can cause ARP conflicts and unstable connectivity for one or both devices.",
    difficulty: "medium",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "What does a subnet mask help a networked device determine?",
    options: ["Which addresses are local versus reached through a router", "Battery chemistry", "ECG gain", "Protective-earth resistance"],
    answer: 0,
    explanation: "The subnet mask identifies the network portion of an IP address and whether a destination is on the local subnet.",
    difficulty: "medium",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "A device connects to Wi-Fi but repeatedly drops when moved between access-point coverage areas. What should be evaluated?",
    options: ["Roaming behavior, signal coverage, authentication, and wireless configuration", "Defibrillator energy", "Infusion accuracy", "Power-cord polarity only"],
    answer: 0,
    explanation: "Mobility-related drops point toward wireless coverage/roaming and authentication/configuration rather than unrelated clinical functions.",
    difficulty: "hard",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "Why should default passwords on network-capable medical equipment be changed when supported and required by policy?",
    options: ["To increase screen brightness", "To reduce unauthorized-access risk", "To improve battery runtime", "To calibrate sensors"],
    answer: 1,
    explanation: "Default credentials are widely known or predictable and can create avoidable security risk.",
    difficulty: "easy",
    category: "cbet",
    topic: "cybersecurity",
  },
  {
    question: "A vendor asks a technician to connect an unknown USB drive to a clinical device for a software update. What is the BEST action?",
    options: ["Connect it immediately", "Follow approved change-control/cybersecurity procedures and verify the update media/source", "Disable antivirus first", "Copy personal files to the drive"],
    answer: 1,
    explanation: "Software updates should use authorized media and controlled procedures to reduce malware, integrity, and configuration risk.",
    difficulty: "medium",
    category: "cbet",
    topic: "cybersecurity",
  },
  {
    question: "A medical device is suspected of malware infection but is still communicating on the clinical network. What is the BEST initial response?",
    options: ["Erase logs immediately", "Follow the organization\u2019s incident-response process and coordinate containment without compromising patient safety", "Post the password publicly", "Ignore it until PM is due"],
    answer: 1,
    explanation: "Cybersecurity incidents require coordinated containment, evidence preservation, and patient-safety consideration under the organization\u2019s response process.",
    difficulty: "hard",
    category: "cbet",
    topic: "cybersecurity",
  },
  {
    question: "What is the purpose of a MAC address in Ethernet/Wi-Fi networking?",
    options: ["Identify a network interface at the data-link layer", "Set AC line voltage", "Measure blood pressure", "Define battery capacity"],
    answer: 0,
    explanation: "A MAC address is a link-layer identifier associated with a network interface.",
    difficulty: "medium",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "A device receives an address beginning with 169.254.x.x when it normally uses DHCP. What does this commonly indicate?",
    options: ["It could not obtain a DHCP lease and self-assigned a link-local address", "Its battery is overcharged", "Its ECG amplifier is saturated", "Its fuse is open"],
    answer: 0,
    explanation: "169.254.x.x is commonly an automatic link-local address used when DHCP assignment fails.",
    difficulty: "hard",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "Why is accurate time synchronization important for networked medical devices?",
    options: ["It improves plastic durability", "It supports reliable event correlation, logs, alarms, and clinical records", "It increases transformer efficiency", "It lowers oxygen consumption"],
    answer: 1,
    explanation: "Consistent timestamps are important when correlating events across devices and clinical information systems.",
    difficulty: "medium",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "A networked monitor works on one switch port but not another using the same cable and configuration. What is the BEST next step?",
    options: ["Compare switch-port configuration/VLAN/status and physical link on the failing port", "Replace the monitor battery", "Recalibrate ECG", "Change the NIBP cuff"],
    answer: 0,
    explanation: "Port-specific behavior points toward switch configuration, VLAN, port security, or physical-layer issues at that port.",
    difficulty: "hard",
    category: "cbet",
    topic: "networking",
  },
  {
    question: "What is the main cybersecurity purpose of network segmentation for medical devices?",
    options: ["Increase mains voltage", "Limit unnecessary communication paths and reduce the impact of compromise", "Improve sensor calibration", "Eliminate the need for passwords"],
    answer: 1,
    explanation: "Segmentation can restrict traffic and reduce lateral movement or exposure if a device or system is compromised.",
    difficulty: "hard",
    category: "cbet",
    topic: "cybersecurity",
  },
  {
    question: "Before installing a vendor software patch on a clinical device, the technician should FIRST:",
    options: ["Apply it to every device without review", "Confirm authorization, compatibility, backup/change-control requirements, and the vendor/facility procedure", "Disable all alarms permanently", "Change the device serial number"],
    answer: 1,
    explanation: "Controlled patching protects clinical function and configuration while ensuring the update is approved and supported.",
    difficulty: "hard",
    category: "cbet",
    topic: "cybersecurity",
  },
  {
    question: "Which chamber pumps oxygenated blood into systemic circulation?",
    options: ["Right atrium", "Right ventricle", "Left atrium", "Left ventricle"],
    answer: 3,
    explanation: "The left ventricle ejects oxygenated blood into the aorta and systemic circulation.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "Which structure normally initiates the heartbeat in a healthy heart?",
    options: ["AV node", "SA node", "Bundle branches", "Purkinje fibers"],
    answer: 1,
    explanation: "The sinoatrial node is the normal primary pacemaker of the heart.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "On a normal ECG, the QRS complex primarily represents:",
    options: ["Atrial depolarization", "Ventricular depolarization", "Ventricular repolarization", "Mechanical valve closure"],
    answer: 1,
    explanation: "The QRS complex corresponds primarily to ventricular depolarization.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "Pulse oximetry estimates arterial oxygen saturation primarily by analyzing:",
    options: ["Electrical impedance of the chest", "Light absorption at different wavelengths through pulsatile tissue", "Blood pressure oscillations", "Carbon dioxide pressure directly"],
    answer: 1,
    explanation: "Pulse oximeters use wavelength-dependent light absorption and the pulsatile arterial component to estimate SpO2.",
    difficulty: "medium",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "A capnograph primarily measures and displays:",
    options: ["Exhaled carbon dioxide over time", "Arterial blood pressure", "Blood glucose", "Electrical cardiac activity"],
    answer: 0,
    explanation: "Capnography measures CO2 in respiratory gas and displays its concentration/partial pressure over the respiratory cycle.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "Which blood vessel carries deoxygenated blood from the right ventricle toward the lungs?",
    options: ["Aorta", "Pulmonary artery", "Pulmonary vein", "Superior vena cava"],
    answer: 1,
    explanation: "The pulmonary artery carries deoxygenated blood from the right ventricle to the lungs.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "Invasive arterial blood pressure monitoring requires the pressure transducer to be leveled and zeroed primarily to:",
    options: ["Reduce hydrostatic measurement error and establish atmospheric reference", "Increase oxygen saturation", "Change heart rate", "Improve network connectivity"],
    answer: 0,
    explanation: "Leveling controls hydrostatic offset and zeroing establishes the atmospheric reference for pressure measurement.",
    difficulty: "hard",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "Why can patient motion interfere with pulse-oximetry readings?",
    options: ["Motion can create optical pulsations/artifact that compete with the arterial signal", "Motion changes AC line frequency", "Motion changes the device IP address", "Motion opens the protective-earth conductor"],
    answer: 0,
    explanation: "Pulse oximetry relies on detecting a small pulsatile optical signal, so motion can create competing artifact.",
    difficulty: "medium",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "The diaphragm\u2019s primary role in normal breathing is to:",
    options: ["Generate the main pressure change that draws air into the lungs during inspiration", "Pump blood through the pulmonary artery", "Control the SA node", "Measure carbon dioxide"],
    answer: 0,
    explanation: "Diaphragm contraction enlarges the thoracic cavity and creates the pressure gradient for inspiration.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "A patient simulator used for ECG testing primarily provides:",
    options: ["Controlled electrical waveforms that mimic cardiac signals", "Actual patient blood pressure", "Real oxygenated blood", "Mechanical ventilation"],
    answer: 0,
    explanation: "ECG simulators generate known electrical waveforms so monitor acquisition, rate, alarms, and related functions can be evaluated.",
    difficulty: "easy",
    category: "cbet",
    topic: "physiology",
  },
  {
    question: "A device fails only after operating for about 20 minutes and works again after cooling. What type of fault is MOST likely?",
    options: ["Thermal/intermittent electronic fault", "Asset-tag problem", "Guaranteed network-license issue", "Cleaning residue only"],
    answer: 0,
    explanation: "A repeatable warm-up/cool-down pattern strongly suggests a temperature-dependent component, connection, or circuit fault.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device repeatedly returns with the same failure after the same board is replaced. What should the technician do?",
    options: ["Continue replacing the board indefinitely", "Reassess the root cause and investigate upstream/downstream conditions that may be causing the failure", "Delete previous service records", "Assume the user is responsible"],
    answer: 1,
    explanation: "Repeated recurrence after board replacement suggests the board may be a symptom rather than the underlying cause.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A service report says \u201cunable to duplicate,\u201d but the clinical user can reproduce the problem consistently. What should be improved FIRST?",
    options: ["Complaint details and reproduction conditions", "Asset label color", "Screen brightness", "PM sticker location"],
    answer: 0,
    explanation: "Detailed conditions, sequence, accessories, environment, and symptoms are essential for reproducing intermittent complaints.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device intermittently fails self-test only after transport between departments. Which approach is BEST?",
    options: ["Inspect connectors/mounting and reproduce the failure while simulating controlled movement", "Replace the battery without testing", "Disable self-test", "Assume user error"],
    answer: 0,
    explanation: "A transport-dependent fault suggests loose connections, mechanical stress, or movement-sensitive components.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A monitor powers on but one subsystem is completely dead. What is the BEST general troubleshooting strategy?",
    options: ["Replace every board", "Verify inputs/power rails and trace the signal/power path toward the failed subsystem", "Increase fuse rating", "Reset the device repeatedly without measurements"],
    answer: 1,
    explanation: "Systematic troubleshooting begins with known inputs and power, then follows the functional path to isolate the failed stage.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device works correctly on the bench but fails in the clinical area. What should the technician investigate?",
    options: ["Environmental, accessory, network, power, workflow, and use-condition differences", "Only the device color", "Only the service manual revision", "Nothing; bench testing proves the complaint is false"],
    answer: 0,
    explanation: "Differences between bench and clinical conditions can expose power, accessory, environmental, configuration, network, or workflow-dependent failures.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A replacement board fixes the symptom, but the original board shows a burned component. What is the BEST next question?",
    options: ["What caused the component to fail?", "Can the service record be deleted?", "Can a larger fuse prevent future failures?", "Should alarms be disabled?"],
    answer: 0,
    explanation: "Root-cause analysis asks whether another fault, load, supply problem, environment, or design condition caused the visible damage.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A technician is troubleshooting an intermittent device and changes three variables at once. Why is this poor practice?",
    options: ["It makes it difficult to identify which change affected the symptom", "It always damages the device", "It prevents any measurements", "It changes the serial number"],
    answer: 0,
    explanation: "Controlled troubleshooting changes one variable at a time when practical so cause and effect can be established.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device fails a test only when a specific accessory is attached. What is the BEST next step?",
    options: ["Evaluate the accessory, interface, and compatibility using a known-good comparison when available", "Replace the main board immediately", "Ignore the accessory", "Increase AC line voltage"],
    answer: 0,
    explanation: "Accessory-dependent failures should be isolated by testing the accessory/interface and comparing with known-good components.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A newly replaced battery has poor runtime. Which check should occur before assuming the new battery is defective?",
    options: ["Verify charging operation, battery type/compatibility, charge state, and device load", "Replace the display", "Change the network VLAN", "Bypass the charger"],
    answer: 0,
    explanation: "Poor runtime can result from charging faults, wrong battery type, incomplete charge, abnormal device load, or a defective battery.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device produces a burning odor during testing but continues to operate. What should the technician do?",
    options: ["Continue until it fails", "De-energize/remove it from service and inspect for overheating or component damage", "Increase cooling with compressed oxygen", "Return it if all buttons work"],
    answer: 1,
    explanation: "A burning odor can indicate overheating or electrical damage and warrants immediate safe shutdown and investigation.",
    difficulty: "medium",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device has a complaint of \u201crandom shutdown.\u201d Logs show shutdowns occur whenever battery voltage falls below a threshold. What should be investigated FIRST?",
    options: ["Battery condition, charging system, connections, and power-management behavior", "ECG lead placement", "NIBP cuff size", "Speaker volume"],
    answer: 0,
    explanation: "The log correlation points directly toward the battery/power path and should guide focused testing.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A technician replaces a sensor and the reading is still wrong. What is the BEST next step?",
    options: ["Verify the reference/test setup and trace the entire measurement chain rather than replacing more parts at random", "Replace the same sensor again", "Adjust calibration until the displayed value looks reasonable", "Ignore the discrepancy"],
    answer: 0,
    explanation: "Persistent error after sensor replacement calls for systematic verification of reference, wiring, excitation, signal conditioning, conversion, and configuration.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device passes all tests after repair, but the technician cannot reproduce the original complaint. What is the BEST documentation approach?",
    options: ["Document the complaint, tests performed, conditions used, findings, and disposition accurately", "State that the user was wrong", "Delete the complaint", "Record only \u201cfixed\u201d"],
    answer: 0,
    explanation: "Clear documentation should preserve the reported symptom and objectively describe the investigation and results.",
    difficulty: "medium",
    category: "cbet",
    topic: "service",
  },
  {
    question: "Which approach BEST supports root-cause repair instead of repeated temporary fixes?",
    options: ["Trend failures, reproduce conditions, use evidence to isolate the failed stage, then verify the repair", "Reset the breaker and return the device each time", "Replace random accessories", "Skip final verification"],
    answer: 0,
    explanation: "Root-cause troubleshooting uses reproducible evidence and verification rather than repeated resets or random parts replacement.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A technician finds a loose connector and reseats it, restoring operation. What should happen next?",
    options: ["Determine why it loosened, inspect for damage, secure as specified, and complete verification", "Return it immediately with no testing", "Glue every connector in place", "Delete prior failure history"],
    answer: 0,
    explanation: "Restoring function is not enough; the cause, connector condition, retention, and complete post-repair performance should be addressed.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
  {
    question: "A device has multiple stored error codes. What is the BEST way to use them?",
    options: ["Correlate codes with timestamps, symptoms, service information, and controlled testing rather than replacing parts from codes alone", "Replace every component named in any code", "Clear them before reading", "Assume the oldest code caused the current failure"],
    answer: 0,
    explanation: "Error codes are diagnostic clues and should be interpreted in context with symptoms, history, and verification testing.",
    difficulty: "hard",
    category: "cbet",
    topic: "troubleshooting",
  },
];

const extraCategories = [
  "eye",
  "ear",
  "arterial system",
  "lungs",
  "liver",
  "kidney",
  "venous system",
  "cbet",
];

const allCategories = Array.from(
  new Set([...allQuestions.map((q) => q.category), ...extraCategories])
).sort();

const equipmentQuestions = [
  {
    image: "/equipment/anesthesia machine.jpg",
    question: "Identify this equipment.",
    options: ["Anesthesia machine", "Ventilator", "Defibrillator", "Suction machine"],
    answer: 0,
    studyTip: "Used to deliver inhaled anesthetics, oxygen, and ventilation support during procedures.",
  },
  {
    image: "/equipment/defibrillator.jpg",
    question: "Identify this equipment.",
    options: ["Patient monitor", "Defibrillator", "Infusion pump", "ECG machine"],
    answer: 1,
    studyTip: "Used to deliver controlled shocks for life-threatening arrhythmias.",
  },
  {
    image: "/equipment/ekg machine.jpg",
    question: "Identify this equipment.",
    options: ["ECG/EKG machine", "Pulse oximeter", "Ventilator", "Fetal monitor"],
    answer: 0,
    studyTip: "Records electrical activity of the heart using surface electrodes.",
  },
  {
    image: "/equipment/electrosurgical unit.jpg",
    question: "Identify this equipment.",
    options: ["Syringe pump", "Electrosurgical unit", "Anesthesia machine", "Ultrasound machine"],
    answer: 1,
    studyTip: "Provides high-frequency electrical energy for cutting/coagulation in surgery.",
  },
  {
    image: "/equipment/fetal monitor.jpg",
    question: "Identify this equipment.",
    options: ["Fetal monitor", "Patient monitor", "Infusion pump", "Defibrillator"],
    answer: 0,
    studyTip: "Tracks fetal heart rate and uterine contractions during pregnancy/labor.",
  },
  {
    image: "/equipment/infusion pump.jpg",
    question: "Identify this equipment.",
    options: ["Infusion pump", "Suction regulator", "Pulse oximeter", "Ventilator"],
    answer: 0,
    studyTip: "Delivers IV fluids and medications at controlled rates.",
  },
  {
    image: "/equipment/patient monitor.jpg",
    question: "Identify this equipment.",
    options: ["Defibrillator", "Patient monitor", "Ultrasound machine", "ECG machine"],
    answer: 1,
    studyTip: "Displays vital signs such as ECG, SpO2, blood pressure, and respiration.",
  },
  {
    image: "/equipment/pulse oximeter.jpg",
    question: "Identify this equipment.",
    options: ["Pulse oximeter", "Syringe pump", "Suction machine", "Anesthesia machine"],
    answer: 0,
    studyTip: "Measures oxygen saturation (SpO2) and pulse rate noninvasively.",
  },
  {
    image: "/equipment/suction machine.jpg",
    question: "Identify this equipment.",
    options: ["Ventilator", "Suction machine", "Patient monitor", "Defibrillator"],
    answer: 1,
    studyTip: "Provides negative pressure to remove fluids/secretions from airways or surgical fields.",
  },
  {
    image: "/equipment/suction regulator.jpg",
    question: "Identify this equipment.",
    options: ["Suction regulator", "Pulse oximeter", "Infusion pump", "Fetal monitor"],
    answer: 0,
    studyTip: "Controls and limits wall-vacuum suction pressure for safe clinical use.",
  },
  {
    image: "/equipment/syringe pump.jpg",
    question: "Identify this equipment.",
    options: ["Syringe pump", "ECG machine", "Electrosurgical unit", "Anesthesia machine"],
    answer: 0,
    studyTip: "Accurately delivers small-volume medications using a loaded syringe.",
  },
  {
    image: "/equipment/ultrasound machine.jpg",
    question: "Identify this equipment.",
    options: ["Ultrasound machine", "Defibrillator", "Patient monitor", "Suction regulator"],
    answer: 0,
    studyTip: "Uses high-frequency sound waves to generate real-time diagnostic images.",
  },
];

const rnQuestions = [
  {
    question: "Which patient should the nurse see first?",
    options: [
      "A client with COPD and an oxygen saturation of 88%",
      "A client with a cast reporting itching",
      "A client requesting pain medication for chronic back pain",
      "A client asking for discharge instructions",
    ],
    answer: 0,
  },
  {
    question: "Which finding requires immediate intervention?",
    options: [
      "Client with a temperature of 99.1°F",
      "Post-op client with urine output of 20 mL/hr",
      "Client with mild nausea after lunch",
      "Client requesting help to the bathroom",
    ],
    answer: 1,
  },
  {
    question: "Which action is most important when administering insulin?",
    options: [
      "Shake the vial vigorously",
      "Administer before verifying the meal tray",
      "Check the blood glucose level first",
      "Massage the injection site",
    ],
    answer: 2,
  },
  {
    question: "Which lab value is most concerning?",
    options: ["Sodium 138 mEq/L", "Calcium 9.2 mg/dL", "Glucose 102 mg/dL", "Potassium 6.2 mEq/L"],
    answer: 3,
  },
  {
    question: "A client receiving warfarin should be monitored for:",
    options: ["Bleeding", "Bradycardia", "Hypoglycemia", "Constipation"],
    answer: 0,
  },
  {
    question: "Which symptom is expected with hypoglycemia?",
    options: ["Dry flushed skin", "Cool clammy skin", "Bradycardia", "Decreased hunger"],
    answer: 1,
  },
  {
    question: "Which client is highest priority?",
    options: [
      "Client with a sprained ankle",
      "Client requesting a blanket",
      "Client with chest pain and diaphoresis",
      "Client with chronic constipation",
    ],
    answer: 2,
  },
  {
    question: "The nurse should question which prescription?",
    options: [
      "Acetaminophen for fever",
      "Normal saline bolus for hypotension",
      "Oxygen for shortness of breath",
      "Potassium for a client with potassium of 5.8",
    ],
    answer: 3,
  },
  {
    question: "Which finding suggests fluid volume overload?",
    options: ["Crackles in the lungs", "Flat neck veins", "Dry mucous membranes", "Poor skin turgor"],
    answer: 0,
  },
  {
    question: "Which intervention is appropriate for seizure precautions?",
    options: [
      "Place a tongue blade at bedside",
      "Pad side rails",
      "Restrain the client during seizure",
      "Keep the room brightly lit",
    ],
    answer: 1,
  },
  {
    question: "Which patient statement shows understanding of digoxin teaching?",
    options: [
      "I should take an extra dose if I miss one",
      "I can stop it when I feel better",
      "I will check my pulse before taking it",
      "Blurred vision means the medicine is working",
    ],
    answer: 2,
  },
  {
    question: "A client with suspected stroke should receive priority for:",
    options: [
      "A high-protein snack",
      "Passive range-of-motion exercises",
      "Routine bedtime medications",
      "Rapid neurologic assessment",
    ],
    answer: 3,
  },
  {
    question: "Which position is best for a client with shortness of breath?",
    options: ["High Fowler's", "Supine", "Trendelenburg", "Prone"],
    answer: 0,
  },
  {
    question: "Which action prevents infection most effectively?",
    options: [
      "Wearing a mask at all times",
      "Hand hygiene",
      "Using sterile gloves for all care",
      "Keeping the room door closed",
    ],
    answer: 1,
  },
  {
    question: "A nurse is caring for a client with a potassium of 2.9 mEq/L. The priority assessment is:",
    options: ["Bowel sounds", "Vision changes", "Cardiac rhythm", "Skin color"],
    answer: 2,
  },
  {
    question: "Which finding is expected with dehydration?",
    options: ["Bounding pulses", "Jugular vein distention", "Pulmonary crackles", "Tachycardia"],
    answer: 3,
  },
  {
    question: "Which nursing action is appropriate when transfusing blood?",
    options: [
      "Stay with the client during the first 15 minutes",
      "Infuse with dextrose solution",
      "Warm blood in a microwave if cold",
      "Start slowly after one hour",
    ],
    answer: 0,
  },
  {
    question: "Which patient is at highest risk for falls?",
    options: [
      "A teenager with a sprained wrist",
      "An older adult taking sedatives",
      "A middle-aged adult with a headache",
      "A child with a sore throat",
    ],
    answer: 1,
  },
  {
    question: "Which finding suggests anaphylaxis?",
    options: ["Mild rash on one arm", "Low-grade fever", "Wheezing and facial swelling", "Constipation"],
    answer: 2,
  },
  {
    question: "A nurse should hold which medication for a pulse of 52/min?",
    options: ["Acetaminophen", "Cefazolin", "Docusate", "Metoprolol"],
    answer: 3,
  },
];

const cbetQuestions = allQuestions.filter((q) => q.category === "cbet");
export { allQuestions, allCategories, equipmentQuestions, extraCategories, rnQuestions, cbetQuestions };
